### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by jithin-j** [jithin-j/VueJS-CoursePro#1]
The site is not optimized for mobile responsiveness. 

- The whole site is messy when viewed on a mobile screen
- Enhance the landing page
- Render the most popular courses as rows in mobile view
- Make the form responsive

**Comment by markus-gx** [comment]
You can assign this to me if you want ;) I guess I am allowed to install tailwind? Because in some components you are using inline html style which could be refactored nicely.

**Comment by jithin-j** [comment]
> You can assign this to me if you want ;) I guess I am allowed to install tailwind? Because in some components you are using inline html style which could be refactored nicely.

Sure :)

**Comment by markus-gx** [comment]
@jithin-j if there are any questions on the PR let me know :)

**Comment by jithin-j** [comment]
@markus-gx I have cloned the repo after merging your pr. But the mobile view looks the same as before. Is there anything I have to run besides "npm i" to ensure tailwind is being used?

**Comment by markus-gx** [comment]
@jithin-j 
`npm i` to install

`npm run serve` to run the dev server (should already work there)

And as I can see, you have the "dist/" folder in version control, maybe you started your express server without building the project? Run `npm run build` to build the project again. And start your express server with `npm run start`

**Comment by jithin-j** [comment]
Yes, the issue is solved now. The website looks very good in mobile view! Thanks a lot for the contribution @markus-gx! Really appreciate it :) Closing this issue now..
